### ISSUE TITLE
📝 Leaving Standard - Ensure all dory tasks are done when someone leaves

### ISSUE THREAD

**Issue by Jord-Gui** [SSWConsulting/SSW.Dory#10]
Good idea raised by @JeanThirion that a use case for the list of outstanding tasks from SSW.Dory is that people leaving the company should have a step to close off their ones when offboarding.

**Comment by Tanya-Leahy** [comment]
Done - added to Leaving Standard on SugarLearning. All leaving staff will now be directed to the Dory SharePoint list to check if they have any outstanding PR's or checked out SharePoint pages and asked to action them.
