### ISSUE TITLE
♻️ GitHub flow targeting draft PRs

### ISSUE THREAD

**Issue by Jord-Gui** [SSWConsulting/SSW.Dory#35]
Cc: @JackDevAU @bradystroud @leahy268 

The GitHub flow is picking up draft PRs. As per feedback from @wicksipedia, we should discuss this.

```[tasklist]
### Tasks
- [ ] Refactor Dory to ignore draft PRs
```

**Comment by Jord-Gui** [comment]
@bradystroud has mentioned that it could pick up Draft PRs that have no updates on them for e.g. more than 2 weeks.

**Comment by wicksipedia** [comment]
I don't know if it was or not... was a general question

**Comment by Jord-Gui** [comment]
As per discussion with @adamcogan, draft PRs are non-blocking so can be ignored by Dory.

**Comment by Jord-Gui** [comment]
I've created another PBI #58 to investigate Power Automate flows marking GitHub PRs as stale

**Comment by Jord-Gui** [comment]
Done - flow now filters our draft PRs
