### ISSUE TITLE
✨ Create SSW.Dory Logo

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Dory#36]
cc @adamcogan 

As per meeting between @Jord-Gui @tiagov8 @bradystroud @JackDevAU 

- [x] 1. Create SSW.Dory logo
- [x] 2. Get it approved
- [x] 3. Add to https://ssw.com.au/ssw/logo/ 
- [x] 4. Add to https://sswconsulting.github.io/SSW.Dory/ (to be updated to its own domain)

PBI for Designers: https://ssw.visualstudio.com/SSW.Design/_workitems/edit/83895

**Comment by Tanya-Leahy** [comment]
Already done:


![Image](https://github.com/SSWConsulting/SSW.Dory/assets/168160851/531d5bb2-0a9e-4669-9b32-662efce05fe0)

**Figure: SSW Dory Logos on SSW website**
