### ISSUE TITLE
📝 Documentation - follow "Do you make awesome documentation?" rule

### ISSUE THREAD

**Issue by vladislav-kir** [SSWConsulting/SSW.Dory#37]
Cc: @bradystroud, @adamcogan 

Hi Team

### Pain
The documentation only has README, and none of the other files from [Do you make awesome documentation?](https://www.ssw.com.au/rules/awesome-documentation/) rule.

### Tasks

- [x] Add Documentation Files as per [Do you make awesome documentation?](https://www.ssw.com.au/rules/awesome-documentation/)
- [x] Add link to Wiki on readme

### Acceptance Criteria
- The documentation follows [Do you make awesome documentation?](https://www.ssw.com.au/rules/awesome-documentation/) rule

Thanks!

**Comment by Jord-Gui** [comment]
Copy this - https://github.com/SSWConsulting/SSW.Website/wiki/Power-Automate-Flows

**Comment by Jord-Gui** [comment]
✅ Done - added the relevant documentation:


![Image](https://github.com/SSWConsulting/SSW.Dory/assets/41951199/6ae343a1-f049-4a2a-bd17-29ddf0e7715e)

**Figure: SSW Dory readme**



![Image](https://github.com/SSWConsulting/SSW.Dory/assets/41951199/9a402f31-1244-4357-be51-9ed14dafd47c)

**Figure: SSW Dory website readme**
