### ISSUE TITLE
♻️ SSW.Dory website - HTTPS

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Dory#49]
- [ ] Make website HTTPS

<img width="460" alt="Screenshot 2023-08-29 at 10 42 32 AM" src="https://github.com/SSWConsulting/SSW.Dory/assets/12601228/b327b5c5-28b7-4d2c-8ffd-1c396fb431ca">

**Comment by Jord-Gui** [comment]
Done


![Image](https://github.com/SSWConsulting/SSW.Dory/assets/41951199/87f892cb-ea6e-42da-81fd-ab987d5498fe)
