### ISSUE TITLE
✨Done replies aren't explained to the user

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.Dory#57]
Cc: @Khaled-Albahsh @leahy268 @adamcogan 

Hi @Jord-Gui 
  
### Pain
As a user, it is unclear why you need to reply done to the email.

Seems like a pointless hoop to jump through.

### Suggested Solution
Either remove replying done
or explain why the user must reply done

### Tasks

- [ ] Investigate and fix

### Acceptance Criteria
No Done reply or done reply is explained

### Screenshots
![image](https://github.com/SSWConsulting/SSW.Dory/assets/79821522/bfa8fe3a-d9f8-43bb-942f-f710acb70e8c)
**Figure: This task isn't explained**

Thanks!

**Comment by Jord-Gui** [comment]
Done - added note that says it's for reporting purposes

![Image](https://github.com/SSWConsulting/SSW.Dory/assets/41951199/56aa0309-a4ba-4f42-a8b9-c637c85012a1)

Figure: SharePoint email

![Image](https://github.com/SSWConsulting/SSW.Dory/assets/41951199/6cde1328-bf27-4adf-9b9b-9e628c87e986)

Figure: GitHub email
